### ISSUE TITLE
Usage instructions for JS newbie

### ISSUE THREAD

**Issue by kill4food** [mckay-software/parse-server-dropbox-adapter#1]
Hi,
I'm very interested in implementing this project in my app to copy images from parse server into a different dropbox access tokens using a cloud function that will be called by user.
I have no knowledge in JS, but parse JS SDK seems to be easy to learn, but i cannot understand how can i implement this project into a cloud function.
My parse server provider could probably install this, but i don't know how to use it.
I couldn't understand what is the use of a public url argument

How could i just get images with a JS query and then upload them into the dropbox access token?
Is there a simple code example for that?
I didn't manage to get the test module to work.

Thanks for the help

**Comment by passcod** [comment]
This module does not do that. It stores all files in a Dropbox folder, bypassing Parse's default file storage. It is highly unlikely that your host, unless you have control over the actual Parse server, would support this. To do what you wish is a completely different project, most definitely requiring JS experience.

More on-topic, the publicUrl is a mirror of how every storage adapter works. When you use the Parse libraries, you either stream files from the Parse server, which this module does, or you get a URL that you can use to reach the file. Parse can also provide that, but you may want to have control over it, for various reasons, from vanity URLs to pointing to caching servers or CDNs for optimising bandwidth. That's what the publicUrl provides for.
